# .rubocop.yml
AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/queue_schema.rb'
    - 'config/initializers/**/*.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

# Enable auto-correctable cops
Layout/TrailingEmptyLines:
  Enabled: true
Layout/LeadingCommentSpace:
  Enabled: true

# Disable complex method metrics if you want to skip them
Metrics/AbcSize:
  Exclude:
    - 'app/controllers/**/*'
Metrics/MethodLength:
  Exclude:
    - 'app/controllers/**/*'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/**/*'

# Optional: ignore OpenStruct warnings if you want
Style/OpenStructUse:
  Exclude:
    - 'app/controllers/members_controller.rb'
